// Generated by CoffeeScript 2.5.1
(function() {
  var cfg, checkDirectoryExists, checkDirectoryIsInGit, checkSomethingExists, exec, execGitCheckPromise, fs, homedir, log, os, pathModule, pathhandlermodule, prepareUserConfigPath, resolveHomeDir, thingyName, utl;

  pathhandlermodule = {
    name: "pathhandlermodule"
  };

  //region modulesFromEnvironment
  //region node_modules
  fs = require("fs-extra");

  pathModule = require("path");

  os = require("os");

  exec = require("child_process").exec;

  //endregion

  //region localModules
  utl = null;

  cfg = null;

  //endregion
  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["pathhandlermodule"] != null) {
      console.log("[pathhandlermodule]: " + arg);
    }
  };

  //endregion
  //#############################################################################
  pathhandlermodule.initialize = async function() {
    log("pathhandlermodule.initialize");
    utl = allModules.utilmodule;
    cfg = allModules.configmodule;
    await prepareUserConfigPath();
  };

  //region internalProperties
  homedir = os.homedir();

  thingyName = "";

  //endregion

  //region internalFunctions
  execGitCheckPromise = function(path) {
    var options;
    options = {
      cwd: path
    };
    return new Promise(function(resolve, reject) {
      var callback;
      callback = function(error, stdout, stderr) {
        if (error) {
          reject(error);
        }
        if (stderr) {
          reject(new Error(stderr));
        }
        return resolve(stdout);
      };
      return exec("git rev-parse --is-inside-work-tree", options, callback);
    });
  };

  prepareUserConfigPath = async function() {
    var dirPath, filePath;
    log("prepareUserConfigPath");
    filePath = resolveHomeDir(cfg.cli.userConfigPath);
    dirPath = pathModule.dirname(filePath);
    await fs.mkdirp(dirPath);
    pathhandlermodule.userConfigPath = filePath;
  };

  resolveHomeDir = function(path) {
    log("resolveHomeDir");
    if (!path) {
      return;
    }
    if (path[0] === "~") {
      path = path.replace("~", homedir);
    }
    return path;
  };

  checkSomethingExists = async function(something) {
    var err;
    try {
      await fs.lstat(something);
      return true;
    } catch (error1) {
      err = error1;
      return false;
    }
  };

  checkDirectoryExists = async function(path) {
    var err, stats;
    try {
      stats = (await fs.lstat(path));
      return stats.isDirectory();
    } catch (error1) {
      err = error1;
      return false;
    }
  };

  checkDirectoryIsInGit = async function(path) {
    var err;
    try {
      await execGitCheckPromise(path);
      return true;
    } catch (error1) {
      err = error1;
      return false;
    }
  };

  //endregion

  //region exposed
  //region exposedProperties
  pathhandlermodule.homedir = homedir; //directory

  pathhandlermodule.userConfigPath = ""; //file

  pathhandlermodule.basePath = ""; //directory

  pathhandlermodule.thingyPath = ""; //directory

  pathhandlermodule.temporaryFilesPath = ""; //directory

  pathhandlermodule.recipesPath = "";

  //endregion

  //region exposedFunctions
  pathhandlermodule.resolve = function(base, other) {
    log("pathhandlermodule.resolve");
    return pathModule.resolve(base, other);
  };

  pathhandlermodule.prepareBasePath = async function(providedPath) {
    var exists, isInGit;
    log("pathhandlermodule.checkBase");
    if (!providedPath) {
      providedPath = cfg.userConfig.defaultThingyRoot;
    }
    providedPath = resolveHomeDir(providedPath);
    if (pathModule.isAbsolute(providedPath)) {
      pathhandlermodule.basePath = providedPath;
    } else {
      pathhandlermodule.basePath = pathModule.resolve(process.cwd(), providedPath);
    }
    log("our basePath is: " + pathhandlermodule.basePath);
    //#sadly this case has gone ;( - it lives on in this comment
    // pathhandlermodule.basePath = process.cwd()
    exists = (await checkDirectoryExists(pathhandlermodule.basePath));
    if (!exists) {
      throw new Error("Provided directory does not exist!");
    }
    isInGit = (await checkDirectoryIsInGit(pathhandlermodule.basePath));
    if (isInGit) {
      throw new Error("Provided directory is already in a git subtree!");
    }
  };

  pathhandlermodule.prepareTemporaryFilesPath = function() {
    log("pathhandlermodule.prepareTemporaryFilesPath");
    pathhandlermodule.temporaryFilesPath = resolveHomeDir(cfg.userConfig.temporaryFiles);
  };

  pathhandlermodule.prepareRecipesPath = function() {
    log("pathhandlermodule.prepareRecipesPath");
    if (!cfg.userConfig.recipesPath) {
      cfg.userConfig.recipesPath = "~/.config/thingyBubble/recipes";
    }
    pathhandlermodule.recipesPath = resolveHomeDir(cfg.userConfig.recipesPath);
  };

  pathhandlermodule.ensureDirectoryExists = async function(directory) {
    var result;
    log("pathhandlermodule.ensureDirectoryExists");
    directory = resolveHomeDir(directory);
    result = (await fs.mkdirp(directory));
  };

  pathhandlermodule.somethingExistsAtBase = async function(name) {
    var something;
    something = pathModule.resolve(pathhandlermodule.basePath, name);
    return (await checkSomethingExists(something));
  };

  pathhandlermodule.directoryExistsAtBase = async function(dirName) {
    var dirPath;
    dirPath = pathModule.resolve(pathhandlermodule.basePath, dirName);
    return (await checkDirectoryExists(dirPath));
  };

  // pathhandlermodule.ensureDirectoryExists = (dirName) ->

  //region oldCode
  pathhandlermodule.checkCreatability = async function(directoryName) {
    var directoryPath, exists;
    directoryPath = pathModule.resolve(pathhandlermodule.basePath, directoryName);
    exists = (await checkDirectoryExists(directoryPath));
    if (exists) {
      throw "The directory at " + directoryPath + " already exists!";
    }
  };

  pathhandlermodule.createInitializationBase = async function(name) {
    thingyName = name;
    pathhandlermodule.thingyPath = pathModule.resolve(pathhandlermodule.basePath, thingyName);
    pathhandlermodule.basePath = pathModule.resolve(pathhandlermodule.basePath, name + "-init");
    return (await fs.mkdirs(pathhandlermodule.basePath));
  };

  pathhandlermodule.cleanInitializationBase = async function() {
    var initializedThingyPath;
    initializedThingyPath = pathModule.resolve(pathhandlermodule.basePath, thingyName);
    await fs.move(initializedThingyPath, pathhandlermodule.thingyPath);
    await fs.remove(pathhandlermodule.basePath);
    return pathhandlermodule.basePath = pathModule.resolve(pathhandlermodule.basePath, "..");
  };

  pathhandlermodule.getBasePath = function() {
    return pathhandlermodule.basePath;
  };

  pathhandlermodule.getGitPaths = function(name) {
    var r;
    r = {};
    r.repoDir = pathModule.resolve(pathhandlermodule.basePath, name);
    r.gitDir = pathModule.resolve(r.repoDir, ".git");
    return r;
  };

  pathhandlermodule.getLicenseSourcePaths = function() {
    var r;
    r = {};
    r.licensePath = pathModule.resolve(__dirname, "LICENSE");
    r.unlicensePath = pathModule.resolve(__dirname, "UNLICENSE");
    return r;
  };

  pathhandlermodule.getLicenseDestinationPaths = function(repoDir) {
    var r;
    r = {};
    r.licensePath = pathModule.resolve(repoDir, "LICENSE");
    r.unlicensePath = pathModule.resolve(repoDir, "UNLICENSE");
    return r;
  };

  pathhandlermodule.setThingyPath = function(path) {
    return pathhandlermodule.thingyPath = path;
  };

  pathhandlermodule.getToolsetPath = function() {
    return pathModule.resolve(pathhandlermodule.thingyPath, "toolset");
  };

  pathhandlermodule.getPreparationScriptPath = function(scriptFileName) {
    return pathModule.resolve(pathhandlermodule.thingyPath, "toolset", scriptFileName);
  };

  //endregion
  //endregion
  //endregion
  module.exports = pathhandlermodule;

}).call(this);
