// Generated by CoffeeScript 2.5.1
(function() {
  var chalk, clear, cliArguments, config, createProcess, figlet, log, olog, ostr, print, printBanner, printError, printSuccess, startupmodule;

  startupmodule = {
    name: "startupmodule"
  };

  //region modulesFromEnvironment
  //region node_modules
  chalk = require('chalk');

  clear = require('clear');

  figlet = require('figlet');

  //endregion

  //region localModules
  createProcess = null;

  config = null;

  cliArguments = null;

  //endregion
  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["startupmodule"] != null) {
      console.log("[startupmodule]: " + arg);
    }
  };

  olog = function(o) {
    return log("\n" + ostr(o));
  };

  ostr = function(o) {
    return JSON.stringify(o, null, 4);
  };

  printSuccess = function(arg) {
    return console.log(chalk.green(arg));
  };

  printError = function(arg) {
    return console.log(chalk.red(arg));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion
  //#############################################################################
  startupmodule.initialize = function() {
    log("startupmodule.initialize");
    createProcess = allModules.createprocessmodule;
    config = allModules.configmodule;
    cliArguments = allModules.cliargumentsmodule;
  };

  //region internalFunctions
  printBanner = function() {
    clear();
    return print(chalk.green(figlet.textSync(config.cli.name, {
      horizontalLayout: 'full'
    })));
  };

  //endregion

  //region exposedFunctions
  startupmodule.cliStartup = async function() {
    var e, err;
    log("startupmodule.cliStartup");
    printBanner();
    try {
      e = cliArguments.extractArguments();
      await createProcess.execute(e.type, e.name, e.basePath, e.configure);
      return printSuccess('All done!');
    } catch (error) {
      err = error;
      printError("Error!");
      printError(err);
      if (err.stack) {
        printError(err.stack);
      }
      return process.exit(-1);
    }
  };

  //endregion exposed functions
  module.exports = startupmodule;

}).call(this);
